version: '3'
services:
  app1:
    container_name: app1
    network_mode: host
    environment:
      APP_PORT: 8081
    image: rksp-pr5-service:0.0.1
  app2:
    container_name: app2
    network_mode: host
    environment:
      APP_PORT: 8082
    image: rksp-pr5-service:0.0.1
  app3:
    container_name: app3
    network_mode: host
    environment:
      APP_PORT: 8083
    image: rksp-pr5-service:0.0.1
  app4:
    container_name: app4
    network_mode: host
    environment:
      APP_PORT: 8084
    image: rksp-pr5-service:0.0.1
  nginx:
    image: nginx:latest
    network_mode: host
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf